### PR TITLE
Feature/add querystring

### PR DESCRIPTION
**Pull request by modpluz**

### CODE REVIEW

**Comment by modpluz** [comment]
These changes let's you make calls like `getResource('candidates', { race_id: 27 });`

**Review by lottspot — COMMENTED** [review]
I was actually just working on the same thing when you opened this PR. I came up with a [slightly less verbose way to implement this](https://github.com/lottspot/leverage-frontend/commit/d75752f5f9e892c0ad4d0a37320cd9eb2a7e95e8). I'll leave it to you to decide which way you like better.

**Comment by modpluz** [comment]
lolz...I just couldn't let it go but I like yours better.

**Comment by lottspot** [comment]
heh... ok, I'll open up a PR from my current branch

**Pull request closed without merging**
